export const LOAD_USERS_START = 'LOAD_USERS_START';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_FILTERED_USERS = 'SET_FILTERED_USERS';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const DELETE_USER = 'DELETE_USER';

export const RESET_STATE = 'RESET_STATE';
